/**
 * Redux Slices exports
 */
export {
  analysisSlice,
  startAnalysis,
  setAssetId,
  analysisCompleted,
  analysisFailed,
  resetAnalysis,
  updateAnalysisState,
  selectAnalysisState,
  selectAnalysisData,
  selectAssetId,
  selectIsAnalyzing,
  selectAnalysisError,
  selectAnalysisDuration,
} from './analysisSlice';
export type { AnalysisSliceState } from './analysisSlice';

export {
  highlightSlice,
  selectCheckpoint,
  setViewMode,
  toggleShowAllHighlights,
  setShowAllHighlights,
  setCurrentHighlightIndex,
  nextHighlight,
  previousHighlight,
  setTotalHighlights,
  setVisibleHighlightIndex,
  cacheHighlight,
  clearExpiredCache,
  clearCache,
  saveScrollPosition,
  openModal,
  closeModal,
  setLoading as setHighlightLoading,
  setError as setHighlightError,
  resetHighlight,
  selectSelectedCheckpoint,
  selectViewMode,
  selectShowAllHighlights,
  selectCurrentHighlightIndex,
  selectTotalHighlights,
  selectVisibleHighlightIndex,
  selectHighlightCache,
  selectScrollPositions,
  selectIsModalOpen,
  selectIsHighlightLoading,
  selectHighlightError,
  selectCachedContent,
  selectScrollPosition,
} from './highlightSlice';
export type { HighlightSliceState, ViewMode, HighlightCacheEntry } from './highlightSlice';

export {
  authSlice,
  setApiKey,
  setWebsiteId,
  setCredentials,
  setSessionToken,
  setRememberMe,
  acknowledgeStorageWarning,
  setAuthLoading,
  setAuthError,
  logout,
  resetAuth,
  hydrateFromStorage,
  selectApiKey,
  selectWebsiteId,
  selectIsAuthenticated,
  selectSessionType,
  selectAccessToken,
  selectRememberMe,
  selectAuthLoading,
  selectAuthError,
  selectStorageWarningAcknowledged,
  STORAGE_KEYS,
} from './authSlice';
export type { AuthSliceState } from './authSlice';

export {
  aiSlice,
  updateSettings,
  setProvider,
  setOpenAIApiKey,
  setOpenAIModel,
  setTranslationProvider,
  setReasoningEffort,
  openSettings,
  closeSettings,
  toggleSettings,
  startGeneration,
  generationCompleted,
  generationFailed,
  clearError as clearAIError,
  clearSummaries,
  clearSummary,
  resetAI,
  hydrateSettings,
  selectAISettings,
  selectAIProvider,
  selectAIEnabled,
  selectOpenAIApiKey,
  selectOpenAIModel,
  selectReasoningEffort,
  selectTranslationProvider,
  selectIsSettingsOpen,
  selectIsGenerating,
  selectGeneratingFor,
  selectAIError,
  selectAllSummaries,
  selectSummary,
  AI_STORAGE_KEYS,
} from './aiSlice';
export type { AISliceState, AISettings, AISummary, AIProvider, TranslationProvider } from './aiSlice';
