name: Publish to NPM

concurrency:
  group: publish
  cancel-in-progress: true

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install dependencies
      run: npm i

    - name: Builds Wiki
      run: npm run wiki:build

    - name: Publish Wiki
      uses: Andrew-Chen-Wang/github-wiki-action@v4
      with:
        commit-message: "Update wiki for version ${{ github.event.release.tag_name }}"
        path: ./wiki

    - uses: actions/checkout@v4
      name: Checkout Probe CLI Repository
      with:
        repository: probelabs/probe
        ref: refs/tags/v0.6.0-rc178
        token: ${{ secrets.CLONE_TOKEN }}
        path: probe

    - name: Build Probe CLI
      working-directory: ./probe
      run: cargo build --release

    - name: Add Probe CLI to PATH
      run: cargo install --path ./probe

    - name: Run Tests
      run: npm test
    
    - name: Build
      run: npm run build
    
    - name: Build MCP Server
      working-directory: ./mcp-server
      run: npm run build
    
    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Publish MCP Server to NPM
      working-directory: ./mcp-server
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
